install.packages('rafalib')
library(rafalib)

install.packages('swirl')
library(swirl)

# Exercício 02
vetorValores <- c(2.23, 3.45, 1.87, 2.11, 7.33, 18.34, 19.23)
media <- mean(vetorValores)

# Exercício 03
soma <- 0
for (i in 1:25) {
  soma <- soma + i^2
}
soma

# Formula
#sum((1:25)^2)


# Exercício 04
cars
class(cars)
# Tipo de objeto é data.frame

# Exercício 05
# quantas linhas vai ter
# 1. nrow() - Número de linhas (mais direto)
# 2. dim() - Dimensões (linhas e colunas)
# 3. length() - Número de elementos (útil para vetores)
nrow(cars)
dim(cars)


# Exercício 06
# Ver todos os nomes das colunas primeiro
names(cars)

#ou
colnames(cars)

# a segunda coluna se chama speed



# Exercício 07
# media da distancia, distancia é coluna 3 (2)
mean(cars[,2])

#ou pelo nome
mean(cars$dist)



# Exercício 07
# O which() em R retorna os índices (número das linhas) que satisfazem uma condição lógica.
# distancia de 85 esta em que linha
which(cars$dist == 85)


# Ver a linha inteira:
cars[which(cars$dist == 85), ]


# Usando Markdown
```{r}
soma <- 0
for (i in 1:25) {
  soma <- soma + i^2
}
soma
```
